### ISSUE TITLE
PA review user auth

### ISSUE THREAD

**Issue by michaeljpark93** [michaeljpark93/bingeterest#2]

**Comment by s-pangburn** [comment]
Excellent job with the styling Michael! Everything is on-point! 👌 

- [x] That being said, your errors are kind of hard to read. Especially for the sake of older and vision-impaired people, I would recommend at least making it bold and perhaps darkening the color a little bit for more contrast. That, or find another color, but you'll still probably have to make the letters "bigger" in some way.
- [x] "Already on member?" should be "Already a member?"
- [x] I got a login error on your `/signup` form (I can't sign up from this page either):
![screen shot 2018-08-13 at 9 54 19 am](https://user-images.githubusercontent.com/8031316/44045930-ebea94fa-9ede-11e8-956a-176fd666696e.png)
- [x] Once I create an account (from the splash page), this is what I see (it also didn't create my account):
![screen shot 2018-08-13 at 9 56 01 am](https://user-images.githubusercontent.com/8031316/44046025-29475cde-9edf-11e8-8f68-caaabf71ce8d.png)
- [x] Going to a random url (i.e. `https://bingeterest1.herokuapp.com/#/sdlkfjsdlkfjlsdkjfslk`) should redirect me to root (Hint: use a `<Switch>` in your routes!)

Let me know when you have these things addressed and I'll take another look!

**Comment by michaeljpark93** [comment]
hey stephen can you take a look? I updated my heroku based on the feedback you provided

**Comment by s-pangburn** [comment]
👍
